#ENC[AES256_GCM,data:Z0bWA+dNTczC1/tdzYufgAI4mN1126rs9SVdBsaXZbKDpN2TUrszglgkwz0dMqgBjjKjz0+MdUKnAubihvHjnIbxQ6FlAfP59pCdBe04BBlrhA+p6xP30DFU52hLdw==,iv:rhI1MXJTl6uLHBlj5nQ8JJIs+ULO4zsNtpXLK9IEd5g=,tag:dTQscO0+iD/wf9YqCQolJg==,type:comment]
#ENC[AES256_GCM,data:P1NNGdrOxxbQvB3eIac6ygWzHwMh5lZ9koMbuhugMLrykCXcjdFr6rC+ppU4Llz+cQwV2NPI+og5,iv:gAVcW77r6MVDbM4mb09N2hMGobSbZQ/b8VZOtFgU+Rw=,tag:F1ayB//QBfSwGZt4yFpL2w==,type:comment]
#ENC[AES256_GCM,data:Z/gkwZao02QkUn0fkjVJRbz9RsAW/mECtL2GVK8XMN0TDFaMs2PqWyukZQ78kD93C2nQccq+uyj2M2A0fElabYLPB53hJIahHEe/MC6F/uz6ww==,iv:97HDCG7mob4ErzfUL/7KIDZzdV3zGH983N0xyl2TWLA=,tag:04gSwubi2R11moRaKR60Iw==,type:comment]
#ENC[AES256_GCM,data:a/8ho8LQYdlLHiAYN9jnWBvZBPjcehrfUWzW5ABLZ9/pia+dnVabQKj4eQFz6w3FCJGb+asMzarN0YX4,iv:7LRR9nqCMnREHUdoG64BoEIm1v8o/6SkH6nU7wqeaOg=,tag:Mk3m5+1aPch7Nr08LaarcQ==,type:comment]
#
#ENC[AES256_GCM,data:KhOiDq4oRtTFSiWDXHNk0DCb/FarvvF58yr01Mz+1wx3vHf8IRbovaPd5iHieusXl4ch7Kd+3uzI/Mm5XcK0J0+cXBwUXtTcx7GwE4ata8z7MXFWZI5l8YjuGyiPM2lwNw==,iv:BzJbNjjUe6upw9qMqaSCn0m/44xrjCaMQUSLJCLNqvI=,tag:ieXJwzGh0S4QiDmiM8wEaw==,type:comment]
#ENC[AES256_GCM,data:Xv3hkFUF54ALFby97lodx5vv3KyPP/fbC3Wx9XEJRjtFz3KeebIeNWKzbXudOQJbhTDEMWIyGYGnNAzjslqi+uR6o4jfUbo3RIr1keGBlM+Kv726nLUOuRDaVUwjsct2,iv:+sK6Nrj/r3iZqkNmeXUKhEjj6MQm3pdGL8buHE48Bxw=,tag:yHUcRdIBvxVs57QPtgdX6w==,type:comment]
#ENC[AES256_GCM,data:meF/7bnkFG25jbLaED4HPPym3AUhCkLHJnhBR6qWKbR5VWRaF5ITZW9lgq1LZYWe7CU/taaGZHmYl4S2Ar0JZowu3tugJ2lq,iv:Cy7jCtAVeBK7ePaUaso4a2GRfr2d9olB5JlQRF+HEGM=,tag:RG0dRRlS/mR+yyXj7KOKRA==,type:comment]
#ENC[AES256_GCM,data:4XHdKYZf0SfGspEU3SwWiE2lK0k/cEOzEcKMBJhqoSFOObSjPTHE2AX+cHEbDwL1J+vKhpzFCJTZFt3SXRnGKb8JcT/S2osbHfVAFncLVm8U+cRpSeqPkaox/hs=,iv:mVDVfp2EetrcCXZYdIA1/yMsAYcvC7Gg6CB98+t755c=,tag:H8i9o2UrMw63R6I5VP8aQg==,type:comment]
tunnel:
    token: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMFNRY1paZ0NXVXZKVW5Q
            cmNRZ09mRGc1VTl3VnEwMzBCYVpUYjczNUg4CkM5bFB1T1dBOGwwRFQ4bTJjRllu
            VVB5ZVRtL1BrYUxNMUo4TjhoQmVwekkKLS0tIHdmTlV4NTdSZGVySjlrWnpUTG5B
            aURLUEJkRTJ0WFlSaFFweW1qbFVmd0kKggoBMnrpw7MG/5pRP1gfwEU7lO5VuTX+
            ofp+ObboN3pTOA0FYrKIGbk4PUkWVkBE3LMp1b6h3yMWtZ+U+rBB4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fgfwws7708s2xk0m99ftrajd98py9r62qnldvkklvs4tx5knz3zs4rjnud
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R0diQVByQ0IwdHRncjla
            TytSZnlRUDZHSGRWaldsV2pGY3UxUThHWkdnCjZ1YTc1NVJXcjZwWHVxMjAyMVc1
            T2g2b0tHNW5UbVJTUVp1czhLYVdlNE0KLS0tIHpmYUZaMmtvR2ZjaXR3N0lENzhD
            SytHU1lNRzVZTVVGUytxN1RuZ2k1SEUKe1oWXptv535vIyNoVteJ9MiJGt96mD5B
            7hEDyWO326oFtNpdzaZlYopcc1kSHiV+KyYpjnn5/H6MxVZeuSG6Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mpng9vq3ae3ek6c4l0tes05s8um8yv3lg6j7a2xdwy786vrzap8s4w6hg6
    lastmodified: "2026-06-23T21:32:34Z"
    mac: ENC[AES256_GCM,data:SjUEVITQ2f4q4BcN8Qyxxu+/r+ZdhPHUPrIfJAxpBhUIkHnrF0UMHSfkpnKxvPQZAD52PAJeegseB11/qkOpcTEWfdwbe49AaXCSFlKC7I4lmIRV15vJnmsgDEwm2wNGVz40MI4+XRvFQTQ0+Bx1QU/sD1KpA4IijCyMTu9HTb8=,iv:SUIsfa6+8gLLoCVIyjnsAdlfDZrEhyOIRBR3ZSZ20mE=,tag:h4TodQyKpO1lNTW1v4Yymg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
